### ISSUE TITLE
Build error `No such file or directory`

### ISSUE THREAD

**Issue by Eliot00** [antoniusnaumann/cargo-swift#58]
```
liushu-ffi on  master [✘!+?] is 📦 v0.1.0 via 🦀 v1.79.0 via ❄️  impure (nix-shell-env) 
❯ cargo swift package --skip-toolchains-check --platforms macos -r -n LiushuCore
✔ Building target macOS
    cargo build --target x86_64-apple-darwin --release
    cargo build --target aarch64-apple-darwin --release
    mkdir -p target/universal-macos/release
    lipo target/x86_64-apple-darwin/release/libliushu_ffi.a \
        target/aarch64-apple-darwin/release/libliushu_ffi.a -create -output \
        target/universal-macos/release/libliushu_ffi.a                                                                      x Generating Swift bindings...                                                                                              

Failed due to the following error: 
Could not generate UniFFI bindings for udl files due to the following error: 
 No such file or directory (os error 2)
 ```
 
 Cargo.toml
```toml
[package]
name = "liushu-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]
name = "liushu_ffi"


[dependencies]
uniffi = { version = "0.27.0" }
liushu-core = { git = "https://github.com/Eliot00/liushu.git", branch = "mac-fix" }

[build-dependencies]
uniffi = { version = "0.27.0", features = [ "build" ] }
```

`ls target/*/release` result:
```
build/  deps/  examples/  incremental/  libliushu_ffi.a  libliushu_ffi.d  libliushu_ffi.rlib
```

Dependencies:
- cargo-swift 0.7.1
- uniffi 0.27.0
- rust 1.79.0
