### ISSUE TITLE
Error generating bindings: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Jomy10** [antoniusnaumann/cargo-swift#69]
I am running into the following error:

```
Failed due to the following error:
Could not generate UniFFI bindings for udl files due to the following error:
 No such file or directory (os error 2)
```

## Steps to reproduce:

```tree
├── Cargo.toml
├── build.rs
└── src
    ├── lib.rs
    └── lib.udl
```

**Cargo.toml**
```toml
[package]
name = "expression_interpreter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]
name = "expression_interpreter"

[dependencies]
uniffi = "0.28"

[build-dependencies]
uniffi = { version = "0.28", features = ["build"] }
```

**build.rs**
```rust
fn main() {
    uniffi::generate_scaffolding("./src/lib.udl").unwrap();
}
```

**lib.rs**
```rust
uniffi::include_scaffolding!("lib");

pub struct Executor {
}

impl Executor {
    pub fn new() -> Self {
        Executor {}
    }
}
```

**lib.udl**
```udl
namespace ExpressionInterpreter {};

interface Executor {
  constructor();
};
```

## Full build output:

```sh
✗ cargo swift package -n ExpressionInterpreter -p macos
✔ Building target macOS
    cargo build --target x86_64-apple-darwin
    cargo build --target aarch64-apple-darwin
    mkdir -p target/universal-macos/debug
    lipo target/x86_64-apple-darwin/debug/libexpression_interpreter.a \
        target/aarch64-apple-darwin/debug/libexpression_interpreter.a -create -output \
        target/universal-macos/debug/libexpression_interpreter.a                                                                            x Generating Swift bindings...

Failed due to the following error:
Could not generate UniFFI bindings for udl files due to the following error:
 No such file or directory (os error 2)
```
